# Makefile_hyperv

deploy-vm:
    HYPERV_HOSTNAME=your_hyperv_host HYPERV_USERNAME=your_hyperv_username HYPERV_PASSWORD=your_hyperv_password ansible-playbook -i ansible/inventory_hyperv.ini ansible/deploy_hyperv.yml
